#
#  API and web config
#
DEBUG                   : True
SECRET_KEY              : 'algjsgASKSAGs72385hbq1bnaskghJSGSGASGjkjk898909'
SQLALCHEMY_DATABASE_URI : 'sqlite:///../../data/db/sqlite.db'
GIT_DATA_DIR            : 'data/git/'
SSH_USER                : 'git'
SERVER_NAME_GIT         : 'localhost:5022'
SERVER_NAME_API         : 'localhost:5000'



#
# SSH Daemon
#
SSH_PUBLIC_KEY          : "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAGEArzJx8OYOnJmzf4tfBEvLi8DVPrJ3/c9k2I/Az64fxjHf9imyRJbixtQhlH9lfNjUIx+4LmrJH5QNRsFporcHDKOTwTTYLh5KmRpslkYHRivcJSkbh/C+BR3utDS555mV"
SSH_PRIVATE_KEY         : "-----BEGIN RSA PRIVATE KEY-----\n
MIIByAIBAAJhAK8ycfDmDpyZs3+LXwRLy4vA1T6yd/3PZNiPwM+uH8Yx3/YpskSW\n
4sbUIZR/ZXzY1CMfuC5qyR+UDUbBaaK3Bwyjk8E02C4eSpkabJZGB0Yr3CUpG4fw\n
vgUd7rQ0ueeZlQIBIwJgbh+1VZfr7WftK5lu7MHtqE1S1vPWZQYE3+VUn8yJADyb\n
Z4fsZaCrzW9lkIqXkE3GIY+ojdhZhkO1gbG0118sIgphwSWKRxK0mvh6ERxKqIt1\n
xJEJO74EykXZV4oNJ8sjAjEA3J9r2ZghVhGN6V8DnQrTk24Td0E8hU8AcP0FVP+8\n
PQm/g/aXf2QQkQT+omdHVEJrAjEAy0pL0EBH6EVS98evDCBtQw22OZT52qXlAwZ2\n
gyTriKFVoqjeEjt3SZKKqXHSApP/AjBLpF99zcJJZRq2abgYlf9lv1chkrWqDHUu\n
DZttmYJeEfiFBBavVYIF1dOlZT0G8jMCMBc7sOSZodFnAiryP+Qg9otSBjJ3bQML\n
pSTqy7c3a2AScC/YyOwkDaICHnnD3XyjMwIxALRzl0tQEKMXs6hH8ToUdlLROCrP\n
EhQ0wahUTCk1gKA4uPD6TMTChavbh4K63OvbKg==\n
-----END RSA PRIVATE KEY-----"

